/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.2
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: webview.i

package webview

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef void* swig_type_1;
typedef _gostring_ swig_type_2;
typedef _gostring_ swig_type_3;
typedef _gostring_ swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef void* swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
extern void _wrap_Swig_free_webview_a27492ac5c0a49c8(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_webview_a27492ac5c0a49c8(swig_intgo arg1);
extern swig_intgo _wrap_WEBVIEW_HINT_NONE_webview_a27492ac5c0a49c8(void);
extern swig_intgo _wrap_WEBVIEW_HINT_MIN_webview_a27492ac5c0a49c8(void);
extern swig_intgo _wrap_WEBVIEW_HINT_MAX_webview_a27492ac5c0a49c8(void);
extern swig_intgo _wrap_WEBVIEW_HINT_FIXED_webview_a27492ac5c0a49c8(void);
extern uintptr_t _wrap_webview_create_webview_a27492ac5c0a49c8(swig_intgo arg1, uintptr_t arg2);
extern void _wrap_webview_destroy_webview_a27492ac5c0a49c8(uintptr_t arg1);
extern void _wrap_webview_run_webview_a27492ac5c0a49c8(uintptr_t arg1);
extern void _wrap_webview_terminate_webview_a27492ac5c0a49c8(uintptr_t arg1);
extern void _wrap_webview_dispatch_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_type_1 arg2, uintptr_t arg3);
extern uintptr_t _wrap_webview_get_window_webview_a27492ac5c0a49c8(uintptr_t arg1);
extern uintptr_t _wrap_webview_get_native_handle_webview_a27492ac5c0a49c8(uintptr_t arg1, uintptr_t arg2);
extern void _wrap_webview_set_title_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_type_2 arg2);
extern void _wrap_webview_set_size_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_intgo arg2, swig_intgo arg3, swig_intgo arg4);
extern void _wrap_webview_navigate_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_type_3 arg2);
extern void _wrap_webview_set_user_agent_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_type_4 arg2);
extern void _wrap_webview_set_html_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_type_5 arg2);
extern void _wrap_webview_init_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_type_6 arg2);
extern void _wrap_webview_eval_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_type_7 arg2);
extern void _wrap_webview_bind_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_type_8 arg2, swig_type_9 arg3, uintptr_t arg4);
extern void _wrap_webview_unbind_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_type_10 arg2);
extern void _wrap_webview_return_webview_a27492ac5c0a49c8(uintptr_t arg1, swig_type_11 arg2, swig_intgo arg3, swig_type_12 arg4);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_webview_a27492ac5c0a49c8(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type Webview_hint_t int
func _swig_getWEBVIEW_HINT_NONE() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_WEBVIEW_HINT_NONE_webview_a27492ac5c0a49c8())
	return swig_r
}

var WEBVIEW_HINT_NONE int = _swig_getWEBVIEW_HINT_NONE()
func _swig_getWEBVIEW_HINT_MIN() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_WEBVIEW_HINT_MIN_webview_a27492ac5c0a49c8())
	return swig_r
}

var WEBVIEW_HINT_MIN int = _swig_getWEBVIEW_HINT_MIN()
func _swig_getWEBVIEW_HINT_MAX() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_WEBVIEW_HINT_MAX_webview_a27492ac5c0a49c8())
	return swig_r
}

var WEBVIEW_HINT_MAX int = _swig_getWEBVIEW_HINT_MAX()
func _swig_getWEBVIEW_HINT_FIXED() (_swig_ret int) {
	var swig_r int
	swig_r = (int)(C._wrap_WEBVIEW_HINT_FIXED_webview_a27492ac5c0a49c8())
	return swig_r
}

var WEBVIEW_HINT_FIXED int = _swig_getWEBVIEW_HINT_FIXED()
func Webview_create(arg1 int, arg2 uintptr) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (uintptr)(C._wrap_webview_create_webview_a27492ac5c0a49c8(C.swig_intgo(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Webview_destroy(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_webview_destroy_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0))
}

func Webview_run(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_webview_run_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0))
}

func Webview_terminate(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_webview_terminate_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0))
}

func Webview_dispatch(arg1 uintptr, arg2 _swig_fnptr, arg3 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	C._wrap_webview_dispatch_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), C.swig_type_1(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func Webview_get_window(arg1 uintptr) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_webview_get_window_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func Webview_get_native_handle(arg1 uintptr, arg2 Webview_native_handle_kind_t) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	swig_r = (uintptr)(C._wrap_webview_get_native_handle_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1)))
	return swig_r
}

func Webview_set_title(arg1 uintptr, arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_webview_set_title_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), *(*C.swig_type_2)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Webview_set_size(arg1 uintptr, arg2 int, arg3 int, arg4 Webview_hint_t) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_webview_set_size_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.swig_intgo(_swig_i_2), C.swig_intgo(_swig_i_3))
}

func Webview_navigate(arg1 uintptr, arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_webview_navigate_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), *(*C.swig_type_3)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Webview_set_user_agent(arg1 uintptr, arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_webview_set_user_agent_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), *(*C.swig_type_4)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Webview_set_html(arg1 uintptr, arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_webview_set_html_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), *(*C.swig_type_5)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Webview_init(arg1 uintptr, arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_webview_init_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Webview_eval(arg1 uintptr, arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_webview_eval_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Webview_bind(arg1 uintptr, arg2 string, arg3 _swig_fnptr, arg4 uintptr) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_webview_bind_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), *(*C.swig_type_8)(unsafe.Pointer(&_swig_i_1)), C.swig_type_9(_swig_i_2), C.uintptr_t(_swig_i_3))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Webview_unbind(arg1 uintptr, arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_webview_unbind_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), *(*C.swig_type_10)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func Webview_return(arg1 uintptr, arg2 string, arg3 int, arg4 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3
	_swig_i_3 := arg4
	C._wrap_webview_return_webview_a27492ac5c0a49c8(C.uintptr_t(_swig_i_0), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_1)), C.swig_intgo(_swig_i_2), *(*C.swig_type_12)(unsafe.Pointer(&_swig_i_3)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg4
	}
}


type SwigcptrWebview_native_handle_kind_t uintptr
type Webview_native_handle_kind_t interface {
	Swigcptr() uintptr;
}
func (p SwigcptrWebview_native_handle_kind_t) Swigcptr() uintptr {
	return uintptr(p)
}

